# -*- coding: utf-8 -*-
{
    "name": "Rocío - Gestión de hermanos",
    "version": "18.0.1.0.1",
    "summary": "Gestión de hermanos y generación de cuotas",
    "category": "Tools",
    "author": "Manuel Calero, Ivan Parrado, Xtendoo",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "account",
        "sale",
        "product",
        "account_payment_mode",
        "account_payment_order",
        "account_payment_sale",
        "account_banking_mandate",
        "account_banking_pain_base",
        "account_banking_sepa_credit_transfer",
        "account_banking_sepa_direct_debit",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/res_partner_view.xml",
        "views/res_partner_leave_reason_view.xml",
        "views/res_config_settings_view.xml",
        "views/menus.xml",
        "wizards/hermano_invoice_wizard_view.xml",
        "wizards/hermano_import_wizard_view.xml",
        "views/menus_actions.xml",
        "data/product_data.xml",
        "data/payment_mode_data.xml",
        "report/report_paperformat_a5.xml",
        "report/recibo_cuota_hermano_template.xml",
        "report/recibo_cuota_hermano_report.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
